"""Build every asset and export it to assets/models/.

Run headless:

    blender --background --python tools/blender/build_all.py

Optionally limit the run to specific assets:

    blender --background --python tools/blender/build_all.py -- res_tree unit_settler

Every model in this project is generated by code rather than modelled by hand.
That means the source of truth is a diffable script, a change to proportions is a
one-line edit that regenerates everything consistently, and nobody has to open
Blender to rebuild the game's art.
"""

from __future__ import annotations

import importlib
import os
import sys
import traceback

HERE = os.path.dirname(os.path.abspath(__file__))

# Blender runs this file directly, so the library modules next to it are not on
# the path yet.
for extra in (HERE, os.path.join(HERE, "assets")):
    if extra not in sys.path:
        sys.path.insert(0, extra)

# Order is irrelevant — each asset resets the scene — but keeping it grouped
# makes the log readable.
ASSETS = [
    "res_tree",
    "bld_towncenter",
    "bld_house",
    "bld_storehouse",
    "bld_farm",
    "bld_barracks",
    "bld_range",
    "bld_tower",
    "unit_settler",
]


def _requested():
    """Asset names after the ``--`` separator, or all of them."""
    if "--" not in sys.argv:
        return ASSETS

    wanted = sys.argv[sys.argv.index("--") + 1:]
    unknown = [name for name in wanted if name not in ASSETS]
    if unknown:
        print(f"[build] unknown asset(s): {', '.join(unknown)}")

    return [name for name in wanted if name in ASSETS] or ASSETS


def main() -> int:
    names = _requested()
    print(f"[build] {len(names)} asset(s): {', '.join(names)}")

    failures = []

    for name in names:
        try:
            module = importlib.import_module(name)
            importlib.reload(module)
            module.export()
        except Exception:
            # Keep going: one broken asset should not hide the state of the rest.
            print(f"[build] FAILED: {name}")
            traceback.print_exc()
            failures.append(name)

    if failures:
        print(f"[build] {len(failures)} of {len(names)} failed: {', '.join(failures)}")
        return 1

    print(f"[build] all {len(names)} assets exported")
    return 0


if __name__ == "__main__":
    sys.exit(main())
